//
//  StaticCategoriesData.swift
//  QLOGA
//
//  Created by Dmitry Mikhailov on 4/13/22.
//

import UIKit
var StaticCategories: [Int: CategoryService] = [

    330: CategoryService(id: 330, sortOrder: 1, name: "Emergency boiler repair",
                         descr: "Professional will come to  your house and try their hardest to fix your boiler as soon as possible.",  unit: "hour",  unitDescr: "Hour",
                         subject: "Boiler, gas lines and pipes, gas valve, etc.",  works: "Gas boiler repair or replacement (including ordering parts and installation).",  exclusions: "Service person may not be able to  repair the boiler if there are no parts available in stock."  ),

    320: CategoryService(id: 320, sortOrder: 2, name: "Non-emergency boiler repair or installation",  descr: "Full gas central heating installations, replacements or repair, connecting boiler to the heating system, setting up optimal pressure, testing heating piping.",  unit: "hour",  unitDescr: "Hour",  subject: "Boilers, radiators, heating pipes, valves, gas pipes, etc.",  works: "Central heating installations, replacements or repair, heating system cleansing and power flushing, setting up optimal gas and water pressure, and further system testing.",  exclusions: "This is a non-emergency service, response time is 24hrs+."    ),

    10: CategoryService(id: 10, sortOrder: 1, name: "Complete home cleaning",  descr: "Cleaning and disinfecting surfaces and floors, dusting, vacuuming, mopping including cupboards, skirting boards , mirrors, pictures and ornaments, cleaning and tidying every room in your home including bathrooms",  unit: "hour",  unitDescr: "Hour",  subject: "Covers every room in the house including bathrooms, kitchens, cupboards, box rooms, vestibule, bay windows, lounges bedrooms, skirting boards, doors, carpets and floors.",  works: "Covers every room in the house including bathrooms, kitchens, cupboards, box rooms, vestibule, bay windows, lounges bedrooms, skirting boards, doors, carpets and floors.",  exclusions: "Windows, external areas and surfaces, laundry and ironing, fireplaces and chimney sweeping, dish washing, unsafe areas, electronic equipment, deep carpet cleaning, animal waste removal [pre-existing stains, furniture cleaning (except vacuuming), waxing, mould and limescale removals, tops of wardrobes Cleaners will not use ladders or lift heavy objects, only areas reachable from the floor can be cleaned"    ),

    20: CategoryService(id: 20, sortOrder: 2, name: "Bathroom and toilet cleaning",  descr: "Toilet, bath, sink, shower or bath cleaning and disinfecting. Includingtiles and floor, drains, taps, windows and mirrors, mould and limescale removals, etc.",  unit: "room",  unitDescr: "Room",  subject: "Toilets, bathrooms, baths, showers. sinks, mirrors, internal windows and glass, flooring and tiles.",  works: "Cleaning, dusting, disinfecting, and toilet bleaching.",  exclusions: "Cleaning significant stains, mould and limescale removals, external sides of windows, bathroom furniture, lights and electronics, and animal waste. Cleaners will not use ladders or lift heavy objects, only areas safely reachable from the floor will be cleaned."),

    30: CategoryService(id: 30, sortOrder: 3, name: "Kitchen cleaning",  descr: "Cleaning kitchen surfaces floors and worktops, dishwashing,, fridges, freezers, hobs, ovens, dishwasher (internals), and inside cupboards.",  unit: "room",  unitDescr: "Room",  subject: "Kitchen and all kitchen surfaces, worktops, fridges, hobs.",  works: "Cleaning and disinfecting surfaces and floors, dish washing, freezer and fridge defrosting, emptying bins, etc.",  exclusions: "Cleaning significant stains, mould and limescale removals, external sides of windows, lights and electronics, cast iron pan deep cleaning, internal appliance cleaning (ovens), and animal waste. Cleaners will not use ladders or lift heavy objects, only areas safely reachable from the floor will be cleaned."),

    40: CategoryService(id: 40, sortOrder: 4, name: "Bedroom or living room cleaning",  descr: "Mopping, vacuuming, and dusting including mirrors and internal-sides of windows, wall art, and ornaments.",  unit: "room",  unitDescr: "Room",  subject: "Bedrooms and living rooms only. Including making beds, cleaning the internal-sides of windows,  cupboards, mirrors, pictures and ornaments, floors, chairs, carpets, fireplaces, skirting boards, windowsills, carpets, wardrobes (inside and out), and any wood surfaces.",  works: "General cleaning, disinfecting high-touch surfaces, dusting, vacuuming, mopping, making beds, internal-sdes to windows, waxing etc.",  exclusions: "Laundry and ironing, cleaning any lights and electronics which cannot be turned off, , deep carpet cleaning, removing significant stains,, furniture cleaning (except vacuuming).Cleaners will not use ladders or lift heavy objects, only areas safely reachable from the floor will be cleaned."),

    50: CategoryService(id: 50, sortOrder: 5, name: "Windows cleaning",  descr: "Residential windows cleaning, both internal and external-facing sides",  unit: "window",  unitDescr: "Window",  subject: "Windows cleaning: including conservatories, glass doors and mirrors",  works: "Cleaning, polishing and disinfecting all windows including conservatories, glass doors and mirrors",  exclusions: "Cleaners will only handle areas safe to reach with their equipment",  timeNorm: Optional(20)  ),

    60: CategoryService(id: 60, sortOrder: 6, name: "Deep upholstery and carpet cleaning",  descr: "Furniture upholstery cleaning (leather or fabric) and carpet cleaning, including deep cleaning, stain and odour removal, and disinfecting and anti-bacterial treatments.",  unit: "hour",  unitDescr: "Hour",  subject: "Carpet and furniture cleaning service, including sofas, chairs, beds, bed heads, stools, curtains, rugs, and other leather and fabric furniture",  works: "Cleaning, vacuuming, dusting, stain and odour removal, disinfecting, and deep cleaning of all leather and fabric carpets and furniture",  exclusions: "Cleaners will only handle areas safe to reach and can only commit to helping with normal, removable stains."    ),

    70: CategoryService(id: 70, sortOrder: 7, name: "Clothes laundry and ironing",  descr: "Family laundry and ironing, steaming and dry cleaning for clothes and bedsheets",  unit: "hour",  unitDescr: "Hour",  subject: "Clothes cleaning (laundry and ironing) including ironing, steaming, pressing and dry cleaning for any underwear, trousers, pants, shirts, t-shirts, bed sheets, and pillows",  works: "Laundry, ironing, steaming, pressing and dry cleaning",  exclusions: "Cleaners will only handle clothing that is able to be washed in a machine and can only commit to helping with normal, removable stains.” Please agree on who provides ironing equipment. This needs to be specified in either notes or in the service conditions"    ),

    400: CategoryService(id: 400, sortOrder: 1, name: "Pet sitting",  descr: "Visiting your house and looking after your pet whilst you are away",  unit: "pet",  unitDescr: "Cat, Dog, Bird, etc",  subject: "Your cat, dog, bird, or other pets",  works: "Coming to your house and looking after your pet. Including feeding, cuddling, brushing and socializing with your cat, dog, bird or other pet. Also includes feeding and changing the water for your pets, taking them to the vet in an emergency, administering any medicines. your pet requires, and changing the cat litter tray",  exclusions: "The service price does not include any veterinary treatments, the customer will have to pay vet charges directly. Unless specified in the service conditions the food needs to be provided by the owner. No aggressive, dangerous or illegal pets."),

    410: CategoryService(id: 410, sortOrder: 2, name: "Dog walking",  descr: "Dog walking services to help your dog exercise and stay healthy while you are away.",  unit: "pet",  unitDescr: "Cat, Dog, Bird, etc",  subject: "Dog",  works: "Morning or evening dog walking, collection from and returning to the owner\'s residence. While walking, dogs are restrained by a collar around their neck or harness. In case of emergency, the carer will take the dog to the vet.",  exclusions: "The service does not include any food, veterinary treatments, and the customer will have to pay vet charges directly. No agressive, dangerous or illegal pets."    ),

    430: CategoryService(id: 430, sortOrder: 3, name: "Cat grooming",  descr: "Get your cat washed, groomed, and looking like a star",  unit: "pet",  unitDescr: "Cat, Dog, Bird, etc",  subject: "Cat",  works: "Brushing out of dead hair, trim and grooming of all dead hair, cutting off hair knots, de-matting, cleaning of the fur, ears and eyes cleaning, cutting nails, general bathing, drying and styling.",  exclusions: "This service does not include applying any veterinary shampoos or treatments, all pets must have healthy hair and skin. No aggressive, dangerous or illegal pets"    ),

    415: CategoryService(id: 415, sortOrder: 4, name: "Doggy day care",  descr: "Whole-day dog care: pick up at residence, morning walk, playing throughout the day, feeding, evening walk, and return to residence.",  unit: "pet",  unitDescr: "Cat, Dog, Bird, etc",  subject: "Dog",  works: "Service includes morning pickup and walk, day feeding, playing and petting throughout the day, evening walk, returning dog back to owner.",  exclusions: "The service does not include any veterinary treatments, vet charges have to be paid directly.No aggressive, dangerous or illegal pets."    ),

    420: CategoryService(id: 420, sortOrder: 4, name: "Dog grooming",  descr: "Get your dog washed, groomed, and looking like a star",  unit: "pet",  unitDescr: "Cat, Dog, Bird, etc",  subject: "Dog",  works: "Brushing out of dead hair, trim and grooming of all dead hair, cutting off hair knots, de-matting, cleaning of the fur, ears and eyes cleaning, cutting nails, general bathing, drying and styling.",  exclusions: "This service does not include applying any veterinary shampoos or treatments, all pets must have healthy hair and skin. No aggressive, dangerous or illegal pets."    ),

    310: CategoryService(id: 310, sortOrder: 1, name: "Emergency plumbing",  descr: "Water leaks and burst pipes, blocked toilets, sinks, pipes and drains, low water pressure, tap radiator and washing machine replacement and installations, and other emergency repairs.",  unit: "hour",  unitDescr: "Hour",  subject: "Pipes, toilets, sinks, baths, showers, boilers, radiators, washing machines, and dishwashers.",  works: "Replacing and installation of boilers, taps, toilets, sinks, pipes, valves, toilets, showers, baths, dishwashers, and washing machines.",  exclusions: "Full central heating installation and specialist internal repairs for toilets, showers, baths, dishwashers, and washing machines are excluded."    ),

    300: CategoryService(id: 300, sortOrder: 2, name: "Non-emergency plumbing",  descr: "Water leaks and burst pipes, blocked toilets, sinks, drains, low water pressure, tap, radiator, dishwasher and washing machine replacement and installations.",  unit: "hour",  unitDescr: "Hour",  subject: "Pipes, toilet, sinks, basins, sewage, boilers, radiators, shower, washing machines, dishwashers.",  works: "Replacement and installation of boilers, taps, valves, toilets, showers, baths, dishwashers, and washing machines.",  exclusions: "This is a non-emergency service with a response time of 24hrs. External drains and sewers and full boiler installation and repair services are excluded."    ),

    340: CategoryService(id: 340, sortOrder: 5, name: "Drain and sewer repair",  descr: "Internal and external drains and sewers repairs including blockage removals, pipe replacements, etc.",  unit: "hour",  unitDescr: "Hour",  subject: "internal and external drains, sewers and pipes",  works: "Internal and external drain and sewer repair, including unblocking and cleaning and replacing drains, sewers and pipes.",  exclusions: "The cost of pipes and other materials is an additional charge, fixing water supply pipes not included."    ),

    500: CategoryService(id: 500, sortOrder: 1, name: "Small home repairs",  descr: "Repairing and wide range of things in the home: furniture, appliances, objects, cracks, painting, decorating, etc.",  unit: "hour",  unitDescr: "Hour",  subject: "Home furniture, appliances, walls, and floors.",  works: "Installing mirrors, paintings, lights, replacing bulbs, easy fixing of windows, doors, and door handles",  exclusions: "No electric, gas, plumbing or construction works which require any special qualifications"    ),

    510: CategoryService(id: 510, sortOrder: 2, name: "Furniture assembly",  descr: "Building flat-packs, easy woodworking projects and anything related furniture assembly",  unit: "hour",  unitDescr: "Hour",  subject: "Home furniture",  works: "Assembling wardrobes, beds, sofas, tables and desks, cabinets, drawers, stools and chairs assembly, shelves. Also hanging artwork, doors, windows and other easy fixes around the home",  exclusions: "No house repairs are included"    ),

    600: CategoryService(id: 600, sortOrder: 1, name: "Math tuition",  descr: "Private tutor to help primary or secondary school students progress their understanding of mathematics and prepare for exams.",  unit: "hour",  unitDescr: "Hour",  subject: "subj",  works: "Personalised lesson plans from an expert in maths taught in your home. Includes help, exercises and practice in the following areas: formulas, key concepts, applied mathematics, analytics, and exam prep.",  exclusions: "Tutors will not provide pens, books, paper, calculators, computers, and other class supplies."    ),

    610: CategoryService(id: 610, sortOrder: 2, name: "English tuition",  descr: "Private tutor to help primary or secondary school students progress their understanding of English literature and language and prepare for exams.",  unit: "hour",  unitDescr: "Hour",  subject: "English grammar and grammatical concepts, reading, pronunciation, writing, figurative language, literature, etc.",  works: "Personalised lesson plans from an expert in English taught in your home. Includes helping with pronunciation, reading, writing, literature, exam and literature prep.",  exclusions: "Tutors will not provide pens, books, paper, computers, and other class supplies."    ),

    620: CategoryService(id: 620, sortOrder: 3, name: "Spanish language tuition",  descr: "Private tutor to help primary or secondary school students improve their Spanish language understanding, speaking and listening, and prepare for exams.",  unit: "hour",  unitDescr: "Hour",  subject: "Lessons focused on studying and practicing Spanish grammar, vocabulary, pronunciation, reading, speaking, listening and achieving fluency.",  works: "Personalised lesson plans from an expert in Spanish taught in your home. Includes help, exercises and practice in the following areas: pronunciation and speaking, reading and writing, grammar, listening, and exam prep.",  exclusions: "Tutors will not provide pens, books, paper, computers, and other class supplies."    ),

    630: CategoryService(id: 630, sortOrder: 4, name: "German language tuition",  descr: "Private tutor to help primary or secondary school students improve their German language understanding, speaking and listening, and prepare for exams.",  unit: "hour",  unitDescr: "Hour",  subject: "Lessons focused on studying and practicing German grammar, vocabulary, pronunciation, reading, speaking, listening and achieving fluency.",  works: "Personalised lesson plans from an expert in German taught in your home. Includes help, exercises and practice in the following areas: pronunciation and speaking, reading and writing, grammar, listening, and exam prep",  exclusions: "Tutors will not provide pens, books, paper, computers, and other class supplies."    ),

    640: CategoryService(id: 640, sortOrder: 5, name: "Russian language tuition",  descr: "Private tutor to help primary or secondary school students improve their Russian language understanding, speaking and listening, and prepare for exams.",  unit: "hour",  unitDescr: "Hour",  subject: "Lessons focused on studying and practicing Russian grammar, vocabulary, pronunciation, reading, speaking, listening and achieving fluency.",  works: "Personalised lesson plans from an expert in Russian taught in your home. Includes help, exercises and practice in the following areas: pronunciation and speaking, reading and writing, grammar, listening, and exam prep.",  exclusions: "Tutors will not provide pens, books, paper, computers, and other class supplies."    ),

    650: CategoryService(id: 650, sortOrder: 6, name: "Italian language tuition",  descr: "Private tutor to help primary or secondary school students improve their Italian language understanding, speaking and listening, and prepare for exams.",  unit: "hour",  unitDescr: "Hour",  subject: "Lessons focused on studying and practicing ItalianRussian grammar, vocabulary, pronunciation, reading, speaking, listening and achieving fluency.",  works: "Personalised lesson plans from an expert Italian tutor in your home. Includes help, exercises and practice in the following areas: pronunciation and speaking, reading and writing, grammar, listening, and exam prep.",  exclusions: "Tutors will not provide pens, books, paper, computers, and other class supplies."    ),

    660: CategoryService(id: 660, sortOrder: 7, name: "French language tuition",  descr: "Private tutor to help primary or secondary school students improve their French language understanding, speaking and listening, and prepare for exams.",  unit: "hour",  unitDescr: "Hour",  subject: "Lessons focused on studying and practicing French grammar, vocabulary, pronunciation, reading, speaking, listening and achieving fluency.",  works: "Personalised lesson plans from an expert French tutor in your home. Includes help, exercises and practice in the following areas: pronunciation and speaking, reading and writing, grammar, listening, and exam prep.",  exclusions: "Tutors will not provide pens, books, paper, computers, and other class supplies"    ),

    670: CategoryService(id: 670, sortOrder: 8, name: "Chemistry tuition",  descr: "Private science tutor for primary and secondary school students, advancing their chemistry studies and preparing them for exams.",  unit: "hour",  unitDescr: "Hour",  subject: "Lessons focused on studying chemistry at primary or secondary school level, including: terminology, theory, formulas, elements, and everything needed to succeed in exams.",  works: "Personalised lesson plans from an expert chemistry tutor taught in your home. Includes help, exercises and practice in the following areas: theory, formulas, experiments and calculations, elements, and exam prep.",  exclusions: "Tutors will not provide pens, books, paper, computers, scientific tools, and other class supplies."    ),

    680: CategoryService(id: 680, sortOrder: 9, name: "Biology tuition",  descr: "Private science tutor for primary and secondary school students, advancing their biology studies and preparing them for exams.",  unit: "hour",  unitDescr: "Hour",  subject: "Lessons focused on studying biology at primary or secondary school level, including: terminology, theory, formulas, and everything needed to succeed in exams.",  works: "Personalised lesson plans from an expert biology tutor taught in your home. Includes help, exercises and practice in the following areas: theory, formulas and calculations, experiments, and exam prep.",  exclusions: "Tutors will not provide pens, books, paper, computers, scientific tools, and other class supplies."    ),

    690: CategoryService(id: 690, sortOrder: 10, name: "Physics tuition",  descr: "Private science tutor for primary and secondary school students, advancing their physics studies and preparing them for exams.",  unit: "hour",  unitDescr: "Hour",  subject: "Lessons focused on studying physics at primary or secondary school level, including: terminology, theory, formulas, and everything needed to succeed in exams.",  works: "Personalised lesson plans from an expert physics tutor taught in your home. Includes help, exercises and practice in the following areas: theory, formulas and calculations, experiments, and exam prep.",  exclusions: "Tutors will not provide pens, books, paper, computers, scientific tools, and other class supplies."    ),

    700: CategoryService(id: 700, sortOrder: 1, name: "IT handyman",  descr: "Fixing software issues with your computer, tablets or smartphones. Includes  setup, installing and configuring applications, disk cleanups, antivirus advice, and upgrades.",  unit: "hour",  unitDescr: "Hour",  subject: "Desktops, laptops, tablets, smartphones, SmartTVs, gaming consoles, routers and networks.",  works: "Disk cleanup, installing and configuring apps, consultancy on personal computing and digital services. upgrading operating systems (Windows, Mac, etc.)",  exclusions: "No hardware fixes and no liability for broken devices."    ),

    710: CategoryService(id: 710, sortOrder: 2, name: "Home network installation or repair",  descr: "Consultancy on internet network requirements for your home, analysis of current problems, internet speed improvement, and design, repair and installation of home networks.",  unit: "house",  unitDescr: "House",  subject: "Home computer network setup, repair and improvement: from wifi and ethernet to connected devices and internet provider connection.",  works: "Setup, repair and  installation of home networks, including: wifi, ethernet and power lines, connected devices, internet providers.",  exclusions: "Internet service needs to be provided by a 3rd party, only tools provided by our technicians. No liability for broken devices is accepted."    ),

    720: CategoryService(id: 720, sortOrder: 3, name: "Personal/family Website development",  descr: "Professional web design service for the development of an original website for your personal or family’s online presence.",  unit: "service",  unitDescr: "Service",  subject: "Personal or family website",  works: "Agreement on content and style, design of website, purchasing domain and other technical requirement, and publishing the completed website",  exclusions: "Website hosting is not included and all purchases required for creating the website (domains, CMS etc.) will be agreed and priced as additional costs. No dynamic content such as e-shop for instance.",  timeNorm: Optional(240)  ),

    800: CategoryService(id: 800, sortOrder: 1, name: "Gardening",  descr: "Enjoy a beautiful garden with the help of expert gardeners and landscapers.",  unit: "hour",  unitDescr: "Hour",  subject: "Home front and back gardens, lawns, flowers, plants, trees, bushes soil, etc.",  works: "Lawn mowing,,planting, weeding, general landscaping, trimming and pruning, raking and general tidying.",  exclusions: "Gardening anywhere other than your residence, tree surgery or removal, and soil replacement or removal."    ),

    810: CategoryService(id: 810, sortOrder: 2, name: "Tree surgery",  descr: "Cutting down<wbr> and trimming trees",  unit: "hour",  unitDescr: "Hour",  subject: "Any kind of tree care, including removing and surgery on large trees and bushes.",  works: "Trimming, fertilizing, planting, complete removal with roots extraction.",  exclusions: "Tree  healing, any services in a garden not located at your residence, and re-planting foreign trees."),

    820: CategoryService(id: 820, sortOrder: 3, name: "Landscaping",  descr: "Changing your garden’s design and benefit from additional features: patios, decking, lawns, and fencing.",  unit: "hour",  unitDescr: "Hour",  subject: "Garden, soil, trees, bushes, flowers.",  works: "Garden and landscape planning including and implementation. Including soil, planting, patios, decking, lawns, water features, and fencing.",  exclusions: "Any services in a garden not located at your residence. Materials needed for the project will be supplied as an additional and agreed-upon cost."    ),

    100: CategoryService(id: 100, sortOrder: 2, name: "Ladies’ signature haircut",  descr: "Fashionable hair cut, wash, dry and styling services in your home from a high-class women’s hair stylist.",  unit: "haircut",  unitDescr: "Haircut",  subject: "Head hair",  works: "Hair cutting, washing, drying, and styling.",  exclusions: "Max session length is 4 hours",  timeNorm: Optional(240)  ),

    110: CategoryService(id: 110, sortOrder: 1, name: "Ladies’ haircut",  descr: "Hair cut, wash, dry and styling services in your home from a professional women’s hair stylists.",  unit: "haircut",  unitDescr: "Haircut",  subject: "Head hair",  works: "Hair cutting, washing, drying, and styling",  exclusions: "Estimated session length is 60 minutes",  timeNorm: Optional(180)  ),

    120: CategoryService(id: 120, sortOrder: 3, name: "Gents’ haircut",  descr: "Classic barbershop style haircut in your home from a professional barber.",  unit: "haircut",  unitDescr: "Haircut",  subject: "Head hair",  works: "Hair cut and styling with gel.",  exclusions: "Max session length is 30 minutes."),

    130: CategoryService(id: 130, sortOrder: 4, name: "Gents’ signature haircut",  descr: "Fashionable gents hair cut, wash, dry and styling services in your home from a high-class men’s hair stylist",  unit: "haircut",  unitDescr: "Haircut",  subject: "Head hair",  works: "Hair cut, wash, dry, dye and styling.",  exclusions: "Max session length is 180 minutes"    ),

    140: CategoryService(id: 140, sortOrder: 5, name: "Girls’ signature haircut",  descr: "Fashionable hair cut, wash and dry from a high-class hair stylist in your home for girls aged 10 years and under.",  unit: "haircut",  unitDescr: "Haircut",  subject: "Head hair",  works: "Hair cutting, washing, drying, dying and styling.",  exclusions: "Max session length is 180 minutes",  timeNorm: Optional(90)  ),

    150: CategoryService(id: 150, sortOrder: 6, name: "Girls’ haircut",  descr: "Quick hair cut, wash, dry and styling services in your home from a professional women’s hair stylists for girls aged 10 years and under.",  unit: "haircut",  unitDescr: "Haircut",  subject: "Head hair",  works: "Hair cutting, washing, drying, and styling",  exclusions: "Max session length is 30 minutes"),

    160: CategoryService(id: 160, sortOrder: 7, name: "Boys’ haircut",  descr: "Quick hair cut in your home from a professional men’s hair stylists for boys aged 10 years and under.",  unit: "haircut",  unitDescr: "Haircut",  subject: "Head hair",  works: "Hair cut and styling with gel.",  exclusions: "Max session length is 30 minutes"),

    170: CategoryService(id: 170, sortOrder: 8, name: "Bridal haircut",  descr: "Get the perfect haircut and style for your wedding, or another important occasion, performed at your address by a specialist in bridal haircuts and styles.",  unit: "haircut",  unitDescr: "Haircut",  subject: "Head hair",  works: "Hair cutting, washing, conditioning, dyeing, and styling for special occasions",  exclusions: "Max session length is 4 hours",  timeNorm: Optional(240)  ),

    180: CategoryService(id: 180, sortOrder: 9, name: "Groom haircut",  descr: "Get the perfect haircut and style for your wedding, or another important occasion, performed at your address by a specialist in groom haircuts and styles.",  unit: "haircut",  unitDescr: "Haircut",  subject: "Head and facial hair",  works: "Hair cutting, washing, conditioning, dyeing, beard trimming, and styling for special occasions.",  exclusions: "Max session length is 4 hours",  timeNorm: Optional(180)  ),

    190: CategoryService(id: 190, sortOrder: 10, name: "Beard trim",  descr: "Beard trimming and styling",  unit: "haircut",  unitDescr: "Haircut",  subject: "Facial hair",  works: "Beard trimming, waxing, styling, with wet shave.",  exclusions: "Max session length is 45 minutes"    ),

    195: CategoryService(id: 195, sortOrder: 10, name: "Wet shave",  descr: "Get the closest shave possible with the help of an expert barber in your home, performed with a straight-edge razor.",  unit: "haircut",  unitDescr: "Haircut",  subject: "Facial hair",  works: "Beard or mustache trimming, wet facial shave.",  exclusions: "Max session length is 45 minutes"),

    910: CategoryService(id: 910, sortOrder: 1, name: "Shopping",  descr: "Can’t get out of the house? Get help buying food and everyday items. Have a service person arrive at your home, create a shopping list with your assistance and purchase the items from your nearest shop.",  unit: "hour",  unitDescr: "Hour",  subject: "Shopping",  works: "Food and everyday item shopping in the nearest location",  exclusions: "Shop must be no farther than 15 minutes walk from residence. Money required for shopping must be provided."    ),

    920: CategoryService(id: 920, sortOrder: 2, name: "Elderly companion",  descr: "Get professional help with elderly friends and relatives. From casual conversation to accompanying them on hospital visits and other excursions.",  unit: "hour",  unitDescr: "Hour",  subject: "Companionship and assistance for elderly people",  works: "Walking together in the local neighbourhood, engaging conversation and companionship, and visiting public places (including hospital visits).",  exclusions: "The service does not include provision of a car, but a taxi may be used if the customer is happy to pay for it. Any extra expenses related to the service are not included."    ),

    900: CategoryService(id: 900, sortOrder: 3, name: "Elderly care",  descr: "Any non-medical care services for elderly people requiring help with everyday tasks.",  unit: "hour",  unitDescr: "Hour",  subject: "Elderly people",  works: "Assisting with everyday tasks in the home, including: washing clothes and dishes, help bathing and using the bathroom, dressing, and cooking basic meals.",  exclusions: "No medical treatment. Assistant may refuse to do any other type of professional work including cleaning the house.. Assistant will no be obliged to assist outside the residence or pay for any additional expenses."    ),

    930: CategoryService(id: 930, sortOrder: 4, name: "Private chef",  descr: "Cooking nutritional meals for you in your own home.",  unit: "hour",  unitDescr: "Hour",  subject: "All daily meals, including: breakfast, lunch, dinner, tea.",  works: "Basic meal preparation, from meal preparation to washing the dishes.",  exclusions: "Our cooks will not provide the groceries, these can be provided by the customer and agreed upon in advance and any other related expenses will not be in the price. No complex or length recipes will be accepted, cooks may refuse to follow customers’ recipes."    ),

    940: CategoryService(id: 940, sortOrder: 5, name: "Socialising service",  descr: "Service person will commit to spend time and have fun together with the elderly.",  unit: "hour",  unitDescr: "Hour",  subject: "Socialising",  works: "Choosing socialising activities with the elderly, going out, making hand crafts, painting, reading books, discussing the most recent happenings.",  exclusions: "Any expenses co-related to the service are not included"    ),

    950: CategoryService(id: 950, sortOrder: 5, name: "Toddler care (1-2yrs) ",  descr: "Get professional, complete child care for children aged 12-24 months, from feeding and changing nappies to playing and outside activities.",  unit: "hour",  unitDescr: "Hour",  subject: "Your child (aged 12-24 months)",  works: "Feeding, changing nappies, walking and excursions in the local area,, health monitoring, ensuring child safety during all activities, playing with toys and games, conversation and developing communication skills, and all usual babysitting activities.",  exclusions: "Any child requiring care must be healthy, with no known allergies, and a contact phone number is required in case of emergency. A list of care instructions and food must be provided by the customer, and each appointment will last no longer than 4 hours."    ),

    960: CategoryService(id: 960, sortOrder: 5, name: "Toddler care (2-4yrs)",  descr: "Get professional, complete child care for children aged 24-48 months, from feeding and changing nappies to playing and outside activities.",  unit: "hour",  unitDescr: "Hour",  subject: "Your child (2-4yrs)",  works: "Feeding, changing nappies, walking and excursions in the local area, health monitoring, ensuring child safety during all activities, playing with toys and games, conversation and developing communication skills, supervised socializing with other children, and all usual babysitting activities.",  exclusions: "Any child requiring care must be healthy, with no known allergies, and a contact phone number is required in case of emergency. A list of care instructions and food must be provided by the customer, and each appointment will last no longer than 4 hours."    ),

    970: CategoryService(id: 970, sortOrder: 5, name: "Primary school age child babysitting",  descr: "Get professional, complete child care for primary school aged children (primary school age), from feeding and socializing to playing and outside activities.",  unit: "hour",  unitDescr: "Hour",  subject: "Primary school age child",  works: "Feeding, changing nappies, walking and excursions in the local area, health monitoring, ensuring child safety during all activities, playing with toys and games, conversation and developing communication skills, supervised socializing with other children, and all usual babysitting activities.",  exclusions: "Any child requiring care must be healthy, with no known allergies, and a contact phone number is required in case of emergency. A list of care instructions and food must be provided by the customer, and each appointment will last no longer than 4 hours."    ),

    1000: CategoryService(id: 1000, sortOrder: 1, name: "Windows",  descr: "All the work required to cut, install or replace glass window panels and whole windows in your home.",  unit: "window",  unitDescr: "Window",  subject: "Windows (Max size: 2.5m x 2.5m), glass panels and frames, sills, etc.",  works: "Cutting and installing glass panels, frames, sills and parts of a window.",  exclusions: "Craftsmen will not cut out new glass panels and the cost of the glass is not included"    ),

    1010: CategoryService(id: 1010, sortOrder: 2, name: "Doors",  descr: "All the work required for cutting and installing doors and door frames for your home.",  unit: "door",  unitDescr: "Door",  subject: "Doors, door frames, and door hinges (Max door size: 3m x 2m).",  works: "Cutting and installing doors, door frames, hinges, hanging doors, etc.",  exclusions: "Installation of locks is not included."    ),

    1020: CategoryService(id: 1020, sortOrder: 3, name: "Furniture assembly",  descr: "Building flat-packs, easy woodworking projects and anything related to basic furniture assembly.",  unit: "hour",  unitDescr: "Hour",  subject: "Beds, wardrobes, cabinets and cupboards, tables, any type of furniture.",  works: "Assembling wardrobes, beds, sofas, tables and desks, cabinets, drawers, shelves, and stools and chairs assembly.",  exclusions: "Furniture needs to be at customers’ address before the scheduled work date."    ),

    1030: CategoryService(id: 1030, sortOrder: 4, name: "Flooring",  descr: "Laying wooden, laminate or tile flooring in your home.",  unit: "m2",  unitDescr: "Square meter",  subject: "Floor: wooden, laminate, tilet, etc.",  works: "Laying underlay and flooring in your home, sealing floors, etc.",  exclusions: "Floor, underlay and all the required materials must be supplied by the customer and available for the agreed work date.",  timeNorm: Optional(15)  ),

    1100: CategoryService(id: 1100, sortOrder: 1, name: "Indoor lights",  descr: "Installing 1 lights in 1 room",  unit: "service",  unitDescr: "Service",  subject: "Lights, light fittings, switches, bulbs, lampshades, etc.",  works: "Installing or replacing lighting in your home, including lights, light fittings, switches, bulbs, lampshades, wiring and lighting electrics.",  exclusions: "Lights and all other required materials must be supplied by the customer and available for the agreed work date."),

    1110: CategoryService(id: 1110, sortOrder: 2, name: "Power cut investigation",  descr: "Electrician will come to your home and analyse power issues and explain how powercuts can be solved/prevented in the future.",  unit: "service",  unitDescr: "Service",  subject: "subj",  works: "Power, power cuts, home electrics, fuses, power issues, etc",  exclusions: "No repairs, only analysis."),

    1120: CategoryService(id: 1120, sortOrder: 3, name: "Power socket installation",  descr: "Electrician will install power/plug sockets in your home, and connect lights to the power source.",  unit: "room",  unitDescr: "Room",  subject: "Power supply, plug/power sockets, basic wiring, lights, etc.",  works: "Installation of power/plug sockets in your home, includes basic wiring, connecting lights to power sources, etc",  exclusions: "Required materials must be supplied by the customer and available for the agreed work date."    ),

    1130: CategoryService(id: 1130, sortOrder: 4, name: "Outdoor lights",  descr: "Electrician will fix, replace or connect electricity to any outdoor lights at your home address.",  unit: "service",  unitDescr: "Service",  subject: "Outdoor lights including: porch lights, garden lights, stair lights, water feature lights, and terrace lights.",  works: "Replacing, installing or connecting all types of electric outdoor lights in your home and garden",  exclusions: "Required materials must be supplied by the customer and available for the agreed work date."    ),

    1200: CategoryService(id: 1200, sortOrder: 1, name: "Changing lock",  descr: "Master locksmith will come to your address and replace the lock in your door.",  unit: "door",  unitDescr: "Door",  subject: "Doors and locks",  works: "Removing original lock and replacing with new lock for any door at your home address.",  exclusions: "Locks and other required materials must be supplied by the customer and available for the agreed work date."    ),

    1210: CategoryService(id: 1210, sortOrder: 2, name: "Key replication",  descr: "Master locksmith master collects your key, replicates it, and returns with the new key(s) to ensure it works.",  unit: "door",  unitDescr: "Door",  subject: "Keys",  works: "Covers the duplication of all types of normal home door keys",  exclusions: "Original keys must be supplied by the customer and available for the agreed work date"),

    1220: CategoryService(id: 1220, sortOrder: 3, name: "Door opening",  descr: "Master locksmith master will open your home’s door for you if the lock breaks or you lose your key.",  unit: "door",  unitDescr: "Door",  subject: "Door, key, lock",  works: "Picking home door locks, breaking locks, door opening at your home address.",  exclusions: "Customer ID required, and customer must be available for the agreed work date."),

    200: CategoryService(id: 200, sortOrder: 1, name: "Ladies manicure",  descr: "Professional ladies nail care session in your home includes: manicure, skin softening procedures, etc.",  unit: "visit",  unitDescr: "One service session",  subject: "Nails on both hands",  works: "Cleaning, clipping, polishing and filing nails, and moisturising hands.",  exclusions: "No Shellac or CND products provided"    ),

    210: CategoryService(id: 210, sortOrder: 2, name: "Ladies signature manicure",  descr: "Professional ladies nail care session in your home from a high-class manicurist includes: manicure, polishing and varnishing with your choice of varnish, and skin softening procedures, etc.",  unit: "visit",  unitDescr: "One service session",  subject: "Nails on both hands",  works: "Cleaning, clipping, polishing and filing nails, applying your choice of nail varnish, and moisturising hands.",  exclusions: "No Shellac or CND products provided."    ),

    220: CategoryService(id: 220, sortOrder: 3, name: "Ladies CND/Shellac manicure",  descr: "Long-lasting manicures with your choice of varnish, includes; nail cleaning and shaping, and hand skin treatments",  unit: "visit",  unitDescr: "One service session",  subject: "Nails on both hands",  works: "Manicure, cleaning, clipping, polishing and filing nails and applying your choice of CND/Shellac nail varnish, and moisturising hands",  exclusions: "exclusions"    ),

    230: CategoryService(id: 230, sortOrder: 4, name: "Ladies pedicure",  descr: "Professional ladies foot care session in your home includes: pedicure, nail cleaning, cutting, polishing and varnishing, and foot soaking, cleaning and skin softening procedures, etc.",  unit: "visit",  unitDescr: "One service session",  subject: "Nails on both feet",  works: "Cleaning, clipping and filing nails, moisturising feet, polishing nails, etc.",  exclusions: "No Shellac or CND products provided"    ),

    240: CategoryService(id: 240, sortOrder: 5, name: "Gents manicure",  descr: "Professional gents’ nail care session in your home. A manicure includes: manicure (nail clipping, shaping, cleaning and polishing), skin softening procedures, etc.",  unit: "visit",  unitDescr: "One service session",  subject: "Nails on both hands",  works: "Cleaning, clipping, filing and shaping nails, moisturising hands, polishing nails (transparent varnish may be used), etc.",  exclusions: "No Shellac or CND products provided"    ),

    250: CategoryService(id: 250, sortOrder: 6, name: "Gents pedicure",  descr: "Professional ladies foot care session in your home includes: pedicure, nail cleaning, cutting, polishing and varnishing, and foot soaking, cleaning and skin softening procedures, etc.",  unit: "visit",  unitDescr: "One service session",  subject: "Nails on both feet",  works: "Cleaning, clipping and filing nails, moisturising feet, polishing nails (transparent nail varnish may be used), etc.",  exclusions: "No Shellac or CND products provided"    )
]
